//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarnetDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgentCollection()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public long ID { get; set; }
        public int AgentID { get; set; }
        public int CreatorID { get; set; }
        public Nullable<int> PayerID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
    }
}
