//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarnetDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentRelatedPayment
    {
        public int AgentID { get; set; }
        public long BillID { get; set; }
        public decimal Allowance { get; set; }
        public decimal ExtraCommission { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Bill Bill { get; set; }
    }
}
