//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarnetDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDFFormItemPlacement
    {
        public int FormType { get; set; }
        public int ItemID { get; set; }
        public decimal CoordsX { get; set; }
        public decimal CoordsY { get; set; }
        public long ID { get; set; }
    }
}
