//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarnetDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.AgentTariffs = new HashSet<AgentTariff>();
            this.ChangeServiceTypeTasks = new HashSet<ChangeServiceTypeTask>();
            this.PartnerAvailableTariffs = new HashSet<PartnerAvailableTariff>();
            this.PartnerRegisteredSubscriptions = new HashSet<PartnerRegisteredSubscription>();
            this.ServiceBillingPeriods = new HashSet<ServiceBillingPeriod>();
            this.ServiceRateTimeTables = new HashSet<ServiceRateTimeTable>();
            this.Subscriptions = new HashSet<Subscription>();
            this.SubscriptionTariffHistories = new HashSet<SubscriptionTariffHistory>();
            this.SubscriptionTariffHistories1 = new HashSet<SubscriptionTariffHistory>();
            this.Domains = new HashSet<Domain>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string RateLimit { get; set; }
        public bool IsActive { get; set; }
        public short InfrastructureType { get; set; }
        public Nullable<short> QuotaType { get; set; }
        public string SoftQuotaRateLimit { get; set; }
        public Nullable<decimal> SmartQuotaMaxPrice { get; set; }
        public Nullable<long> BaseQuota { get; set; }
        public short BillingType { get; set; }
        public int PaymentTolerance { get; set; }
        public int ExpirationTolerance { get; set; }
        public bool NoQueue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentTariff> AgentTariffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangeServiceTypeTask> ChangeServiceTypeTasks { get; set; }
        public virtual ExternalTariff ExternalTariff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerAvailableTariff> PartnerAvailableTariffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerRegisteredSubscription> PartnerRegisteredSubscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceBillingPeriod> ServiceBillingPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRateTimeTable> ServiceRateTimeTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionTariffHistory> SubscriptionTariffHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionTariffHistory> SubscriptionTariffHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Domain> Domains { get; set; }
    }
}
