//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarnetDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionTransferHistory
    {
        public long ID { get; set; }
        public long From { get; set; }
        public long To { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Subscription Subscription { get; set; }
        public virtual Subscription Subscription1 { get; set; }
    }
}
