//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarnetDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionTelekomInfo
    {
        public long SubscriptionID { get; set; }
        public string SubscriptionNo { get; set; }
        public long TTCustomerCode { get; set; }
        public string PSTN { get; set; }
        public string RedbackName { get; set; }
        public Nullable<short> XDSLType { get; set; }
        public Nullable<int> PacketCode { get; set; }
        public Nullable<int> TariffCode { get; set; }
        public Nullable<bool> IsPaperWorkNeeded { get; set; }
        public Nullable<int> OperatorID { get; set; }
    
        public virtual Subscription Subscription { get; set; }
        public virtual TransitionOperator TransitionOperator { get; set; }
    }
}
