//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarnetDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportGroupUser
    {
        public int SupportGroupID { get; set; }
        public int AppUserID { get; set; }
        public bool CanChangeState { get; set; }
        public bool CanRedirect { get; set; }
        public bool CanWriteToCustomer { get; set; }
        public bool CanAssignToStaff { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual SupportGroup SupportGroup { get; set; }
    }
}
