//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarnetDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportRequestProgress
    {
        public long ID { get; set; }
        public long SupportRequestID { get; set; }
        public System.DateTime Date { get; set; }
        public short ActionType { get; set; }
        public Nullable<short> NewState { get; set; }
        public Nullable<short> OldState { get; set; }
        public Nullable<int> SetGroupID { get; set; }
        public string Message { get; set; }
        public bool IsVisibleToCustomer { get; set; }
        public Nullable<int> AppUserID { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual SupportGroup SupportGroup { get; set; }
        public virtual SupportRequest SupportRequest { get; set; }
    }
}
